### ISSUE TITLE
The Typeform API integration is no longer working

### ISSUE THREAD

**Issue by xredo** [MarsBased/typeform-slack-integration#2]
They might have changed the endpoint. We are receiving the following error:

```
/usr/lib/ruby/1.9.1/net/http.rb:763:in `initialize': getaddrinfo: Name or service not known (SocketError)
	from /usr/lib/ruby/1.9.1/net/http.rb:763:in `open'
	from /usr/lib/ruby/1.9.1/net/http.rb:763:in `block in connect'
	from /usr/lib/ruby/1.9.1/timeout.rb:55:in `timeout'
	from /usr/lib/ruby/1.9.1/timeout.rb:100:in `timeout'
	from /usr/lib/ruby/1.9.1/net/http.rb:763:in `connect'
	from /usr/lib/ruby/1.9.1/net/http.rb:756:in `do_start'
	from /usr/lib/ruby/1.9.1/net/http.rb:745:in `start'
	from /usr/lib/ruby/1.9.1/net/http.rb:1285:in `request'
	from /var/lib/gems/1.9.1/gems/httparty-0.13.7/lib/httparty/request.rb:117:in `perform'
	from /var/lib/gems/1.9.1/gems/httparty-0.13.7/lib/httparty.rb:545:in `perform_request'
	from /var/lib/gems/1.9.1/gems/httparty-0.13.7/lib/httparty.rb:476:in `get'
	from /var/lib/gems/1.9.1/gems/slackform-0.1.0/lib/slackform/api_gateway/base.rb:7:in `make_get'
	from /var/lib/gems/1.9.1/gems/slackform-0.1.0/lib/slackform/api_gateway/typeform.rb:15:in `responses'
	from /var/lib/gems/1.9.1/gems/slackform-0.1.0/lib/slackform/slackform_cli.rb:29:in `invite'
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /var/lib/gems/1.9.1/gems/slackform-0.1.0/bin/slackform:5:in `<top (required)>'
	from /usr/local/bin/slackform:23:in `load'
	from /usr/local/bin/slackform:23:in `<main>'
```

The error seems produced in: https://github.com/MarsBased/slackform/blob/master/lib/slackform/api_gateway/typeform.rb

Soeak with Alex for details on how the integration works, and how to test it. Be sure to execute it using "test" data. Don't try to test the integration with the live slackform typeform or it will fail.

**Comment by alexrodba** [comment]
@oriolbcn is back. Worth talking to him instead as I don't know how to test it without the live form.

**Comment by artero** [comment]
@alexrodba @xredo I spoke with @oriolbcn, and he did this issue
